[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'stride'
rpc_addr = 'http://localhost:36657'
grpc_addr = 'http://localhost:10090'
websocket_addr = 'ws://localhost:36657/websocket'
rpc_timeout = '15s'
account_prefix = 'stride'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0, denom = 'ustrd' }
max_gas = 10000000
clock_drift = '5s'
trusting_period = '14day'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'cosmoshub'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9090'
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0, denom = 'uatom' }
max_gas = 10000000
clock_drift = '5s'
trusting_period = '14day'
trust_threshold = { numerator = '1', denominator = '3' }